[package]
name = "rpi-bellsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_glow = "0.31.1"
rppal = "0.22.1"
